name: $(BuildID)

parameters:
  - name: privateAgentName
    displayName: "Agent pool name"
    type: string
    default: 'Azure Pipelines'
  - name: primaryRegion
    displayName: "Primary region"
    type: string
    default: 'UKSouth'
  - name: environments
    type: object
    default:
      - name: 'dp_dev'
        developmentEnvironment: true
      - name: 'dp_tst'
        developmentEnvironment: false
      - name: 'dp_pre'
        developmentEnvironment: false
      - name: 'dp_prd'
        developmentEnvironment: false

trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
    - features/*
    - feat/*

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA/ado-pipeline-common
      endpoint: DEFRA
      type: github
      ref: main
    - repository: GIO_DATA_PLATFORM
      name: GIO_DATA_PLATFORM
      type: git
      ref: main
  
extends:
  template: templates/pipelines/common-infrastructure-deploy.yaml@PipelineCommon
  parameters:
    additionalRepositories:
      -  GIO_DATA_PLATFORM
    variableFiles:
      - /vars/common.yaml@GIO_DATA_PLATFORM
      - /vars/{environment}.yaml@GIO_DATA_PLATFORM
    environments:
      - ${{ each env in parameters.environments }}:
        - name:  ${{ env.name }}
          azureRegions:
            primary: ${{ parameters.primaryRegion }}
          developmentEnvironment: ${{ env.developmentEnvironment }}
          deploymentBranches:
            - '*'
          serviceConnection: ${{ variables.azureResourceManagerConnection }}
    privateAgentName: ${{ parameters.privateAgentName }}
    groupedDeployments:
      - name: Purview_Deployment
        deployments:
         - name: 'Configure Collections'
           serviceConnectionVariableName: azureResourceManagerConnection
           isDeployToSecondaryRegions: false
           path: 'src/infrastructure/scripts/PowerShell/Scripts/Purview/ConfigureCollections.ps1'
           type: script
           scriptType: AzurePowerShell
           scriptArguments: '-ConfigFilePath "$(Build.SourcesDirectory)/GIO_DATA_PLATFORM/src/config/catalogue/Extract/Collections/collections.json" -ImportConfigPath "$(Build.SourcesDirectory)/GIO_DATA_PLATFORM/src/config/catalogue/importConfig.json" -AccountName "$(scriptEnvironment)$(parent-project)$(nc-function-application)PV$(subscriptionNumber)$(regionNumber)01"'
         - name: 'Configure Collection Permissions'
           serviceConnectionVariableName: azureResourceManagerConnection
           isDeployToSecondaryRegions: false
           path: 'src/infrastructure/scripts/PowerShell/Scripts/Purview/ConfigureCollectionPermissions.ps1'
           type: script
           scriptType: AzurePowerShell
           scriptArguments: '-ConfigFilePath "$(Build.SourcesDirectory)/GIO_DATA_PLATFORM/src/config/catalogue/Extract/Collections/Permissions/$(scriptEnvironment)" -AccountName "$(scriptEnvironment)$(parent-project)$(nc-function-application)PV$(subscriptionNumber)$(regionNumber)01"'  
         - name: 'Configure Classifications'
           serviceConnectionVariableName: azureResourceManagerConnection
           isDeployToSecondaryRegions: false
           path: 'src/infrastructure/scripts/PowerShell/Scripts/Purview/ConfigureClassifications.ps1'
           type: script
           scriptType: AzurePowerShell
           scriptArguments: '-ConfigFilePath "$(Build.SourcesDirectory)/GIO_DATA_PLATFORM/src/config/catalogue/Extract/TypeDefinitions/classifications.json" -AccountName "$(scriptEnvironment)$(parent-project)$(nc-function-application)PV$(subscriptionNumber)$(regionNumber)01"'
      #   - name: 'Configure Glossary'
      #     serviceConnectionVariableName: azureResourceManagerConnection
      #     isDeployToSecondaryRegions: false
      #     path: 'src/infrastructure/scripts/PowerShell/Scripts/Purview/ConfigureGlossaries.ps1'
      #     type: script
      #     scriptType: AzurePowerShell
      #     scriptArguments: '-ConfigFilePath "$(Build.SourcesDirectory)/GIO_DATA_PLATFORM/src/config/catalogue/Extract/Glossaries" -AccountName "$(scriptEnvironment)$(parent-project)$(nc-function-application)PV$(subscriptionNumber)$(regionNumber)01"'
