name: $(BuildID)

parameters:
  - name: whatIf
    displayName: PowerShell WhatIf Comparison
    type: boolean
    default: true

  - name: deploy
    displayName: "Deployment"
    type: boolean
    default: false

  - name: region
    displayName: "Region"
    type: string
    default: uksouth
    values:
      - uksouth

# PROJECT SPECIFIC (CHANGE ME ACCORDINGLY)
trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - DEFRA-CPR-PURVIEW/Security/*

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-DEVOPS-COMMON/Defra.Pipeline.Common
      type: git
      ref: refs/tags/Release-v5-latest
    - repository: GIO_DATA_PLATFORM
      name: DEFRA-Common-Platform-Improvements/GIO_DATA_PLATFORM
      type: git
      ref: main
  
extends:
  template: /templates/pipelines/common-scripts-deploy.yaml@PipelineCommon
  parameters:
    variableFiles:
      - /vars/common.yaml@GIO_DATA_PLATFORM
      - /vars/{environment}.uksouth.yaml@GIO_DATA_PLATFORM
    environments:
      - name: 'DP_DEV'
        azureRegions:
          primary: uksouth
        developmentEnvironment: true
        deploymentBranches:
          - '*'
        serviceConnection: AZD-CPR-DEV1
    scriptsList:   
     - displayName: 'Configure Collections and Permissions'
       scriptPath: 'src/infrastructure/scripts/PowerShell/Purview/ConfigureCollections.ps1'
       type: AzurePowerShell
       scriptArguments: '-ConfigFilePath "/GIO_DATA_PLATFORM/src/config/catalogue/$(scriptEnvironment)" -Environment $(scriptEnvironment) -AccountName "$(scriptEnvironment)$(parent-project)$(nc-function-application)PV1001"'
