trigger: none

parameters:
  - name: deployToDevelopmentEnvironment
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: true
  - name: workItemId
    displayName: "The id of the work item (This will be used in the environment name)"
    type: string
    default: ''

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-DEVOPS-COMMON/Defra.Pipeline.Common
      type: git
    - repository: GIO_DATA_PLATFORM
      name: DEFRA-Common-Platform-Improvements/GIO_DATA_PLATFORM
      type: git
      ref: feat/ephemeral-support

extends:
  template: /templates/pipelines/common-infrastructure-deploy.yaml@PipelineCommon
  parameters:
    variableFiles:
      - /src/config/catalogue/vars/ephemeral.yaml@GIO_DATA_PLATFORM
    projectName: Purview Data Catalogue
    deployFromFeature: ${{ parameters.deployToDevelopmentEnvironment }}
    privateAgentName: DEFRA-COMMON-windows2022-SSV3
    environments:
     - name: 'Ephemeral'
       developmentEnvironment: True
       useDevelopmentEnvironmentForValidationOnly: False
       azureRegions:
        primary: NorthEurope
       serviceConnection : AZD-CPR-DEV1
       privateAgentName: DEFRA-COMMON-windows2022-SSV3
    groupedTemplates:
      - name: Purview_Ephemeral_infra
        templates:
          - name: purview
            isDeployToSecondaryRegions: false
            path: src/features/catalogue/infra
            type: bicep
            parameterFilePath: src/features/catalogue/infra
            scope: "Resource Group"
            resourceGroupName: $(resourceGroup)
        postDeployScriptsList:
              - displayName: Add Admin Group to Root Collection Admin
                type: AzurePowerShell
                inlineScript: |
                  az purview account add-root-collection-admin --name $(ephemeralName) --object-id $(adminGroupId) --resource-group $(resourceGroup)