trigger: none

parameters:
  - name: deployToDevelopmentEnvironment
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: true
  - name: workItemId
    displayName: "The id of the work item (This will be used in the environment name)"
    type: string
    default: '12345'

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-DEVOPS-COMMON/Defra.Pipeline.Common
      type: git
    - repository: GIO_DATA_PLATFORM
      name: DEFRA-Common-Platform-Improvements/GIO_DATA_PLATFORM
      type: git
      ref: feat/ephemeral-support

extends:
  template: /templates/pipelines/common-infrastructure-deploy.yaml@PipelineCommon
  parameters:
    variableFiles:
      - /src/config/catalogue/vars/ephemeral.yaml@GIO_DATA_PLATFORM
    projectName: Purview Data Catalogue
    deployFromFeature: ${{ parameters.deployToDevelopmentEnvironment }}
    privateAgentName: DEFRA-COMMON-windows2022-SSV3
    environments:
      - name: 'Ephemeral'
        developmentEnvironment: True
        useDevelopmentEnvironmentForValidationOnly: False
        azureRegions:
          primary: NorthEurope
        serviceConnection: AZD-CPR-DEV1
        privateAgentName: DEFRA-COMMON-windows2022-SSV3
    groupedTemplates:
      - name: Purview_Ephemeral_infra
        templates:
          - name: purview
            isDeployToSecondaryRegions: false
            path: src/features/catalogue/infra
            type: bicep
            parameterFilePath: src/features/catalogue/infra
            scope: "Resource Group"
            resourceGroupName: $(resourceGroup)
            postDeployScriptsList:
              - displayName: Add Permission to ephemeral Group
                type: AzurePowerShell
                inlineScript: |
                  Install-Module -Name Az.Purview -Force
                  Import-Module -Name Az.Purview
                  Add-AzPurviewAccountRootCollectionAdmin -AccountName $(ephemeralName) -ResourceGroupName $(resourceGroup) -ObjectId $(adminGroupId)
                  New-AzRoleAssignment -ObjectId $(adminGroupId) -RoleDefinitionName "Owner" -Scope /subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroup)
                  New-AzRoleAssignment -ObjectId $(adminGroupId) -RoleDefinitionName "Owner" -Scope /subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroup)/providers/Microsoft.Purview/accounts/$(ephemeralName)
                  New-AzRoleAssignment -ObjectId $(adminGroupId) -RoleDefinitionName "Collection administrator" -Scope /subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroup)/providers/Microsoft.Purview/accounts/$(ephemeralName)