name: $(BuildID)

parameters:
  - name: deleteEphemeral
    displayName: " Delete Ephemeral Env after extract"
    type: boolean
    default: true
  - name: workItemId
    displayName: "Work Item Id"
    type: string
    default: 'XXXXXX'

trigger: none
pr: none

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA/ado-pipeline-common
      endpoint: DEFRA
      type: github
      ref: refs/tags/1.0.0
    - repository: GIO_DATA_PLATFORM
      name: DEFRA-Common-Platform-Improvements/GIO_DATA_PLATFORM
      type: git
      ref: feat/${{ parameters.workItemId }}

variables:
  gioRepo: $[ resources.repositories.GIO_DATA_PLATFORM.ref ]
  targetRepoUrl: $[ resources.repositories.GIO_DATA_PLATFORM.url ]
  accountName: $(ephemeralNamePrefix)${{ parameters.workItemId }}

extends:
  template: templates/pipelines/common-infrastructure-deploy.yaml@PipelineCommon
  parameters:
    additionalRepositories:
      -  GIO_DATA_PLATFORM
    variableFiles:
      - /vars/common.yaml@GIO_DATA_PLATFORM
      - /src/config/catalogue/vars/ephemeral.yaml@GIO_DATA_PLATFORM
    deployFromFeature: true
    environments:
      - name: 'Ephemeral'
        developmentEnvironment: True
        useDevelopmentEnvironmentForValidationOnly: False
        azureRegions:
          primary: NorthEurope
    privateAgentName: $(privateAgentName)
    groupedDeployments:
      - name: Purview_Ephemeral_Extract
        deployments:
          - name: 'Replace Tokens in Tokeniser File'
            serviceConnectionVariableName: azureResourceManagerConnection
            isDeployToSecondaryRegions: false
            type: script
            scriptType: AzurePowerShell
            inlineScript: |
                        $jsonFilePath = "$(Build.SourcesDirectory)/GIO_DATA_PLATFORM/src/config/catalogue/importConfig.json"
                        Write-Host $jsonFilePath
                        $jsonContent = Get-Content -Path $jsonFilePath | ConvertFrom-Json
                        $token = $jsonContent.tokens | Where-Object { $_.tokenName -eq "accountName" }

                        if ($token) {
                            $token.tokenValue = "$(accountName)"
                            $jsonContent | ConvertTo-Json | Set-Content -Path $jsonFilePath
                        }
          - name: 'Extract Purview Customisations into local Branch and Create Automatic PR'
            serviceConnectionVariableName: azureResourceManagerConnection
            isDeployToSecondaryRegions: false
            type: script
            scriptType: AzurePowerShell
            path: 'src/infrastructure/scripts/PowerShell/Scripts/Purview/ExtractPurviewCustomisations.ps1'
            scriptArguments: '-TargetRepoUrl $(targetRepoUrl) -RootRepoPath "$(Build.SourcesDirectory)\GIO_DATA_PLATFORM" -FolderPath "$(Build.SourcesDirectory)\GIO_DATA_PLATFORM/src/config/catalogue/Extract" -ExportSettings "$(Build.SourcesDirectory)/GIO_DATA_PLATFORM/src/config/catalogue/exportConfig.json" -AccountName "$(accountName)" -QueuedBy "$(Build.QueuedBy)" -SourceBranch "$(gioRepo)" -AdoAccessToken $(System.AccessToken) -AdoProject $(System.TeamProject) -AdoAccountUrl $(System.CollectionUri)'
          - ${{ if eq(parameters.deleteEphemeral, True) }}:
            - name: 'Delete Ephemeral after extract'
              serviceConnectionVariableName: azureResourceManagerConnection
              isDeployToSecondaryRegions: false
              type: script
              scriptType: AzureCLI
              inlineScript: 'az resource delete -g $(resourceGroup) -n $(accountName) --resource-type "Microsoft.Purview/accounts" --no-wait'
