name: $(BuildID)

parameters:
  - name: configRepositoryName
    displayName: "Configuration Repository Name"
    type: string
    default: 'GIO_DATA_PLATFORM'
  - name: deleteEphemeral
    displayName: " Delete Ephemeral Env after extract"
    type: boolean
    default: true
  - name: workItemId
    displayName: "Work Item Id"
    type: string
    default: 'XXXXXX'

trigger: none
pr: none

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA/ado-pipeline-common
      endpoint: DEFRA
      type: github
      ref: refs/tags/1.0.0
    - repository: ConfigRepository
      name: DEFRA-Common-Platform-Improvements/GIO_DATA_PLATFORM
      type: git
      ref: feat/${{ parameters.workItemId }}

variables:
  configRepositoryName: ${{ parameters.configRepositoryName }}
  configRepositoryBranch: $[ resources.repositories.ConfigRepository.ref ]
  configRepositoryUrl: $[ resources.repositories.ConfigRepository.url ]
  accountName: $(ephemeralNamePrefix)${{ parameters.workItemId }}

extends:
  template: templates/pipelines/common-infrastructure-deploy.yaml@PipelineCommon
  parameters:
    additionalRepositories:
      -  ConfigRepository
    variableFiles:
      - /src/config/catalogue/vars/ephemeral.yaml@ConfigRepository
    deployFromFeature: true
    privateAgentName: DEFRA-COMMON-windows2022-SSV3
    environments:
      - name: 'Ephemeral'
        developmentEnvironment: True
        useDevelopmentEnvironmentForValidationOnly: False
        azureRegions:
          primary: NorthEurope
        serviceConnection: AZD-CPR-DEV1
        privateAgentName: DEFRA-COMMON-windows2022-SSV3
    groupedDeployments:
      - name: Purview_Ephemeral_Extract
        deployments:
          - name: 'Replace Tokens in Tokeniser File'
            isDeployToSecondaryRegions: false
            type: script
            scriptType: AzurePowerShell
            inlineScript: |
                        $jsonFilePath = "$(Build.SourcesDirectory)/ConfigRepository/src/config/catalogue/importConfig.json"
                        Write-Host $jsonFilePath
                        $jsonContent = Get-Content -Path $jsonFilePath | ConvertFrom-Json
                        $token = $jsonContent.tokens | Where-Object { $_.tokenName -eq "accountName" }

                        if ($token) {
                            $token.tokenValue = "$(accountName)"
                            $jsonContent | ConvertTo-Json | Set-Content -Path $jsonFilePath
                        }
          - name: 'Extract Purview Customisations into local Branch and Create Automatic PR'
            isDeployToSecondaryRegions: false
            type: script
            scriptType: AzurePowerShell
            path: 'src/infrastructure/scripts/PowerShell/Scripts/Purview/ExtractPurviewCustomisations.ps1'
            scriptArguments: '-TargetRepoUrl $(configRepositoryUrl) -RootRepoPath "$(Build.SourcesDirectory)\ConfigRepository" -FolderPath "$(Build.SourcesDirectory)\ConfigRepository/src/config/catalogue/Extract" -ExportSettings "$(Build.SourcesDirectory)/ConfigRepository/src/config/catalogue/exportConfig.json" -AccountName "$(accountName)" -QueuedBy "$(Build.QueuedBy)" -SourceBranch "$(configRepositoryBranch)" -AdoAccessToken $(System.AccessToken) -AdoProject $(System.TeamProject) -AdoAccountUrl $(System.CollectionUri) -AdoRepositoryName $(configRepositoryName)'
          - ${{ if eq(parameters.deleteEphemeral, True) }}:
            - name: 'Delete Ephemeral after extract'
              isDeployToSecondaryRegions: false
              type: script
              scriptType: AzureCLI
              inlineScript: 'az resource delete -g $(resourceGroup) -n $(accountName) --resource-type "Microsoft.Purview/accounts" --no-wait'
