name: $(BuildID)

parameters:
  - name: whatIf
    displayName: PowerShell WhatIf Comparison
    type: boolean
    default: true

  - name: deploy
    displayName: "Deployment"
    type: boolean
    default: false

  - name: region
    displayName: "Region"
    type: string
    default: uksouth
    values:
      - uksouth

  - name: workItemId
    displayName: "Work Item Id"
    type: string
    default: 'XXXXXX'

pool: DEFRA-COMMON-windows2022-SSV3

trigger: none
pr: none

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA/ado-pipeline-common
      endpoint: DEFRA
      type: github
      ref: refs/tags/1.0.0
    - repository: GIO_DATA_PLATFORM
      name: DEFRA-Common-Platform-Improvements/GIO_DATA_PLATFORM
      type: git
      ref: feat/${{ parameters.workItemId }}

variables:
  gioRepo: $[ resources.repositories.GIO_DATA_PLATFORM.ref ]
  targetRepoUrl: $[ resources.repositories.GIO_DATA_PLATFORM.url ]
  accountName: $(ephemeralNamePrefix)${{ parameters.workItemId }}

extends:
  template: templates/pipelines/common-infrastructure-deploy.yaml@PipelineCommon
  parameters:
    additionalRepositories:
      -  GIO_DATA_PLATFORM
    variableFiles:
      - /vars/common.yaml@GIO_DATA_PLATFORM
      - src/config/catalogue/vars/ephemeral.yaml@GIO_DATA_PLATFORM
    environments:
      - name: 'DP_DEV'
        azureRegions:
          primary: uksouth
        developmentEnvironment: true
        deploymentBranches:
          - '*'
        serviceConnection: AZD-CPR-DEV1
    groupedDeployments:
      - name: Purview_Ephemeral_infra
        deployments:
          - name: extract-purview-customisations
            isDeployToSecondaryRegions: false
            type: script
            scriptsList:
              - displayName: 'Replace Tokens in Tokeniser File'
                type: AzurePowerShell
                inlineScript: |
                        $jsonFilePath = "$(Build.SourcesDirectory)/GIO_DATA_PLATFORM/src/config/catalogue/importConfig.json"
                        Write-Host $jsonFilePath
                        $jsonContent = Get-Content -Path $jsonFilePath | ConvertFrom-Json
                        $token = $jsonContent.tokens | Where-Object { $_.tokenName -eq "accountName" }

                        if ($token) {
                            $token.tokenValue = "$(accountName)"
                            $jsonContent | ConvertTo-Json | Set-Content -Path $jsonFilePath
                        }
              - displayName: 'Extract Purview Customisations into local Branch and Create Automatic PR'
                scriptPath: 'src/infrastructure/scripts/PowerShell/Scripts/Purview/ExtractPurviewCustomisations.ps1'
                type: AzurePowerShell
                scriptArguments: '-TargetRepoUrl $(targetRepoUrl) -RootRepoPath "$(Build.SourcesDirectory)\GIO_DATA_PLATFORM" -FolderPath "$(Build.SourcesDirectory)\GIO_DATA_PLATFORM/src/config/catalogue/Extract" -ExportSettings "$(Build.SourcesDirectory)/GIO_DATA_PLATFORM/src/config/catalogue/exportConfig.json" -AccountName "$(accountName)" -QueuedBy "$(Build.QueuedBy)" -SourceBranch "$(gioRepo)" -AdoAccessToken $(System.AccessToken) -AdoProject $(System.TeamProject) -AdoAccountUrl $(System.CollectionUri)'
              - displayName: 'Delete Ephemeral after extract'
                inlineScript: 'az purview account delete --name $(accountName) --resource-group $(resourceGroup) --no-wait --yes'
                type: AzureCLI