name: $(BuildID)

trigger: none
pr: none

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA/ado-pipeline-common
      endpoint: DEFRA
      type: github
      ref: refs/tags/1.0.0
    - repository: GIO_DATA_PLATFORM
      name: DEFRA-Common-Platform-Improvements/GIO_DATA_PLATFORM
      type: git
      ref: main

extends:
  template: templates/pipelines/common-infrastructure-deploy.yaml@PipelineCommon
  parameters:
    additionalRepositories:
      -  GIO_DATA_PLATFORM
    variableFiles:
      - /vars/common.yaml@GIO_DATA_PLATFORM
      - /src/config/catalogue/vars/ephemeral.yaml@GIO_DATA_PLATFORM
    deployFromFeature: true
    environments:
      - name: 'Ephemeral'
        developmentEnvironment: True
        useDevelopmentEnvironmentForValidationOnly: False
        azureRegions:
          primary: UkSouth
        serviceConnection: AZD-CPR-DEV1
    privateAgentName: DEFRA-COMMON-windows2022-SSV3
    groupedDeployments:
      - name: TestScripts
        deployments:
          - name: 'script 1'
            serviceConnectionVariableName: azureResourceManagerConnection
            isDeployToSecondaryRegions: false
            type: script
            scriptType: AzurePowerShell
            inlineScript: |
                    Write-Host "Script 1"
          - name: 'script 2'
            serviceConnectionVariableName: azureResourceManagerConnection
            isDeployToSecondaryRegions: false
            type: script
            scriptType: AzurePowerShell
            inlineScript: |
                    Write-Host "Script 2"